### ISSUE TITLE
Unable to find and build mavros-263650d

### ISSUE THREAD

**Issue by davla** [robust-rosin/robust#203]
@ChrisTimperley and @wasowski 

After adding this repo as remote (or local, or even both at the same time with different names) source to bugzoo,
```bash
bugzoo bug list
```
doesn't show any mavros bug. I can see there are branches in this repo with the files necessary to build them, but I have no idea if I have to do something else in order to "activate" them. I'm not familiar with bugzoo internals, and I'm looking for guidance.

**Comment by wasowski** [comment]
@ChrisTimperley I just talked to @davla, he will trye again, but a word from you whether this should work, would be nice.

**Comment by ChrisTimperley** [comment]
@davla Is there a particular set of bugs that you're trying to build? I'm afraid that most of the `mavros` bugs haven't been merged into the `master` branch because their test scripts haven't been written. It is possible to switch to some of the remote branches that host particular `mavros` bugs and to build from there, but I wouldn't encourage that.

If you have a particular use case in mind, I might be able to give a better set of suggestions.

**Comment by davla** [comment]
I need to build the image for `mavros` bug `263650d`.

I don't actually care about the test script, as I'll unleash my own bug finder on the code. My setup already includes docker, so an image with the bug would just be ideal.

Tell me anything I need to do, any help would be very appreciated.

**Comment by ChrisTimperley** [comment]
@davla you should now be able to find and build `263650d`. There are lots of other `mavros` bugs with working Docker images that haven't been merged into `master` because their test scripts haven't been written or finalised. I'll go ahead and merge those bugs without their test scripts over the next few days.

If there any `mavros` bugs in particular that you would like Docker images for, do let me know, and be sure to prioritise those.
