### ISSUE TITLE
BugZoo container launch: Error response from daemon

### ISSUE THREAD

**Issue by git-afsantos** [robust-rosin/robust#47]
This is for bug `ca23e58`. After the fix by @ChrisTimperley , I can successfully build the bug image using bugzoo, as is described in the README of this repo.

`bugzoo bug build --force robust:ca23e58`

After a successful build, I tried to launch the interactive shell, as per the [instructions](https://github.com/robust-rosin/robust/blob/master/doc/testcase.md) also on this repo.

`bugzoo container launch robust:ca23e58`

Unfortunately, I was greeted with an error message, and I am unsure on how to proceed.

> Error response from daemon: Container 436b23b12a3556cf0ea5a06d5320d926640314700c261f21795dd8fe644c9d02 is not running

Did I miss an intermediate step?

**Comment by ChrisTimperley** [comment]
It would appear that due to mishandling of the `IS_BUILD_FAILURE` flag in the `Dockerfile`, the PUT for `ca23e58` was never built, and so the `devel` directory, which was used by the entrypoint script, was never created. I've fixed the `Dockerfile` to always attempt to build, even if a build error is expected, so that a `devel` directory is generated. (In the case of build failure, the outcome of the build is just ignored.)

Now we're back to build issues with this particular bug: #20.
